<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>$(TargetFrameworkVersions)</TargetFrameworks>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <UserSecretsId>$(MSBuildProjectName)-3d3c0583-76c2-4340-8505-3261f0c086cb</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AwesomeAssertions" />
    <PackageReference Include="Bogus" />
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Moq" />
    <PackageReference Include="System.Text.Json" />
    <PackageReference Include="xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\PetToys.DbAssistant.Mssql\PetToys.DbAssistant.Mssql.csproj" />
  </ItemGroup>

</Project>
