<Project>
  <PropertyGroup>
    <RoslinatorVersion>[4.14.0,)</RoslinatorVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Microsoft.Data.SqlClient" Version="[5.2.2,)" />
    <PackageVersion Include="System.Text.Json" Version="[8.0.5,)" />
  </ItemGroup>
  <ItemGroup>
    <GlobalPackageReference Include="Microsoft.SourceLink.GitHub" Version="[8.0.0,)" />
    <GlobalPackageReference Include="Roslynator.Analyzers" Version="$(RoslinatorVersion)" />
    <GlobalPackageReference Include="Roslynator.CodeAnalysis.Analyzers" Version="$(RoslinatorVersion)" />
    <GlobalPackageReference Include="Roslynator.CodeFixes" Version="$(RoslinatorVersion)" />
    <GlobalPackageReference Include="Roslynator.Formatting.Analyzers" Version="$(RoslinatorVersion)" />
    <GlobalPackageReference Include="Roslynator.Refactorings" Version="$(RoslinatorVersion)" />
  </ItemGroup>
</Project>